FROM liquibase/liquibase:4.7
ADD waltz-data/src/main/ddl/liquibase /liquibase/changelog
CMD ["sh", "-c", "docker-entrypoint.sh --url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME} --username=${DB_USER} --password=${DB_PASSWORD} --hub-mode=off  --changeLogFile=../../../liquibase/changelog/${CHANGE_LOG_NAME} update"]
