version: "3.9"
    
services:
  waltz:
    image: ghcr.io/ljubon/waltz:postgresql 
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:11
    environment:
      POSTGRES_DB: "waltz"
      POSTGRES_PASSWORD: "waltz"
      POSTGRES_USER: "waltz"
