name: Question
description: General enquiry
labels: [ "enquiry" ]
body:
  - type: textarea
    id: desc
    attributes:
      label: Description
      description: "Please be as specific as possible to help us answer your questions"
      placeholder: "e.g.: how do I ... ? , does Waltz support ... ?"
    validations:
      required: true
  
