name: Docker

on:
  push:
    branches: [ master ]
  
jobs:
  build:
    name: Build and push Waltz image - postgresql
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: waltz
          POSTGRES_PASSWORD: postgres 
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U waltz -d waltz"
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 10

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Login to GitHub Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build with Maven - postgresql
      run: mvn -B clean package -Pwaltz-postgres,build-postgres,ci -s .build.settings.xml

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:postgresql 
