name: Docker

on:
  push:
    branches: [ master ]
  
jobs:
  build:
    name: Build and test Waltz - postgresql
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: waltz
          POSTGRES_PASSWORD: postgres 
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U waltz -d waltz"
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 10

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build with Maven - postgresql
      run: mvn -B clean package -Pwaltz-postgres,build-postgres,ci -s .build.settings.xml

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: ghcr.io/${{ github.repository }}:postgresql 

    - name: Test image
      run: docker-compose up -d

    - name: Health check
      timeout-minutes: 5
      run: while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8080/waltz-web/)" != "200" ]]; do sleep 5; done

    - name: Verify logs
      if: failure()
      run: | 
        docker-compose logs waltz
        docker-compose logs postgres

    - name: Push image to GitHub Registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:postgresql 

    - name: Stop containers
      if: always()
      run: | 
        docker-compose down
