# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Waltz Build (pg)

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: waltz
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:     
    - uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Cache Maven packages    
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn -B -s .build.settings.xml -Pci,build-postgres,waltz-postgres clean package;

    - name: Publish build
      uses: actions/upload-artifact@v2
      with:
        name: waltz-web-postgres.war
        path: waltz-web/target/waltz-web.war

    - name: Publish liquibase changelogs
      uses: actions/upload-artifact@v2
      with:
        name: liquibase-changelogs
        path: waltz-data/src/main/ddl/liquibase/

    - name: Publish Test Report
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1

    - name: Login to GitHub Registry
      if: ${{ github.ref_type == 'tag' }}
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - id: lowercase
      name: Enforce lowercase for repo name
      if: ${{ github.ref_type == 'tag' }}
      run: |
        echo ::set-output name=REPO_LC::"${repoName,,}"
      env:
        repoName: '${{ github.repository }}'

    - name: Build and push Docker image
      if: ${{ github.ref_type == 'tag' }}
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.ref_type == 'tag' }}
        tags: |
          ghcr.io/$repoName:postgres-${{ github.ref_name }}
          ghcr.io/$repoName:${{ github.ref_name }}
          ghcr.io/$repoName:postgres
          ghcr.io/$repoName:latest
      env:
        repoName: "${{ steps.lowercase.outputs.REPO_LC}}"

    - name: Release
      uses: softprops/action-gh-release@v1
      if: ${{ github.ref_type == 'tag' }}
      with:
        files: |
          waltz-data/target/liquibase-scripts.zip
          waltz-web/target/waltz-web.war
          waltz-web/target/waltz-web-jar-with-dependencies.jar
